[project]
name = "newsdesk-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pymupdf4llm>=0.0.19",
    "ruff>=0.11.3",
    "tiktoken>=0.9.0",
]
